[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

[program:queue-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600 --memory=256
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=%(ENV_QUEUE_WORKERS)s
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stopwaitsecs=60
user=appuser

[program:queue-integration]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work redis --queue=integration --sleep=3 --tries=0 --max-time=3600 --memory=256
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stopwaitsecs=60
user=appuser

[program:scheduler]
process_name=%(program_name)s
command=/bin/sh -c "while true; do php /var/www/artisan schedule:run --verbose --no-interaction >> /dev/stdout 2>&1; sleep 60; done"
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
user=appuser
